'use client';

import React from 'react';
import { Container } from '@/components/ui/Container';
import Link from 'next/link';

export const Footer = () => {
  return (
    <footer className="bg-bg-surface border-t border-border py-12">
      <Container>
        <div className="flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="flex flex-col items-center md:items-start gap-4">
            <div className="text-2xl font-bold text-text-main tracking-tight">
              AI <span className="text-primary">Books</span>
            </div>
            <p className="text-text-muted text-sm max-w-xs text-center md:text-left">
              A curated collection of literature generated by artificial intelligence. 
              Exploring the boundaries of machine creativity.
            </p>
          </div>
          
          <div className="flex gap-8 text-sm font-medium text-text-muted">
            <Link href="/about" className="hover:text-primary transition-colors">
              About
            </Link>
            <a 
              href="https://github.com/prof-lijar/ai-generated-books" 
              target="_blank" 
              rel="noopener noreferrer" 
              className="hover:text-primary transition-colors"
            >
              GitHub
            </a>
            <Link href="/privacy" className="hover:text-primary transition-colors">
              Privacy
            </Link>
          </div>
        </div>
        <div className="mt-12 pt-8 border-t border-border text-center text-text-muted text-xs">
          © {new Date().getFullYear()} AI-Generated Books Platform. All rights reserved.
        </div>
      </Container>
    </footer>
  );
};
