import React from 'react';
import { Container } from '@/components/ui/Container';

export default function AboutPage() {
  return (
    <main className="min-h-screen bg-bg-main py-24 px-4">
      <Container>
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <h1 className="text-4xl font-bold text-text-main mb-6">About AI Books</h1>
            <p className="text-lg text-text-muted mb-8 leading-relaxed max-w-2xl mx-auto">
              The AI-Generated Books Platform is a digital library dedicated to exploring the 
              intersection of artificial intelligence and literature. Our goal is to provide 
              a public space where anyone can browse and read books created by large language models.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
            <div className="space-y-8">
              <section>
                <h2 className="text-2xl font-bold text-text-main mb-4">The AI Book-Writer System</h2>
                <p className="text-text-muted leading-relaxed mb-4">
                  The books in this library are not simply prompted into existence. They are generated by 
                  <span className="text-text-main font-semibold"> book-writer</span>, an autonomous AI multi-agent system 
                  designed for high-quality, long-form content creation.
                </p>
                <p className="text-text-muted leading-relaxed">
                  The system is built using the <span className="text-text-main font-medium">Google ADK (Agent Development Kit)</span> 
                  and leverages locally-running LLM models via <span className="text-text-main font-medium">Ollama</span>, 
                  ensuring a controlled and reproducible generation process.
                </p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-text-main mb-4">From Draft to PDF</h2>
                <p className="text-text-muted leading-relaxed mb-4">
                  Once the chapters are finalized, the <span className="text-text-main font-semibold">Publisher</span> component 
                  takes over. It orchestrates the compilation of individual Markdown chapters into the professional 
                  PDF books available for reading on this platform.
                </p>
                <div className="p-4 bg-primary/10 border border-primary/20 rounded-lg">
                  <p className="text-sm text-text-main">
                    Explore the engine behind the books: <br />
                    <a 
                      href="https://github.com/prof-lijar/orchast_agent/tree/master/book-writer" 
                      className="text-primary hover:underline font-bold break-all"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      github.com/prof-lijar/orchast_agent/tree/master/book-writer
                    </a>
                  </p>
                </div>
              </section>
            </div>

            <div className="bg-bg-surface border border-border rounded-2xl p-8 shadow-sm">
              <h2 className="text-2xl font-bold text-text-main mb-6">The Generation Pipeline</h2>
              <p className="text-sm text-text-muted mb-8">
                Each chapter undergoes a rigorous 4-phase sequential pipeline to ensure depth, 
                coherence, and quality:
              </p>
              <div className="space-y-6">
                <div className="flex gap-4">
                  <div className="flex-shrink-0 w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center font-bold">1</div>
                  <div>
                    <h3 className="font-semibold text-text-main">Outline Agent</h3>
                    <p className="text-sm text-text-muted">Creates a detailed hierarchical plan for the chapter, ensuring all key points are covered.</p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <div className="flex-shrink-0 w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center font-bold">2</div>
                  <div>
                    <h3 className="font-semibold text-text-main">Writer Agent</h3>
                    <p className="text-sm text-text-muted">Transforms the outline into a full, comprehensive chapter draft.</p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <div className="flex-shrink-0 w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center font-bold">3</div>
                  <div>
                    <h3 className="font-semibold text-text-main">Reviewer Agent</h3>
                    <p className="text-sm text-text-muted">Critically analyzes the draft to improve clarity, flow, and narrative consistency.</p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <div className="flex-shrink-0 w-8 h-8 rounded-full bg-primary text-white flex items-center justify-center font-bold">4</div>
                  <div>
                    <h3 className="font-semibold text-text-main">Finalizer Agent</h3>
                    <p className="text-sm text-text-muted">Produces the final polished Markdown output, ready for publication.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-16 grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="p-6 bg-bg-surface border border-border rounded-lg shadow-sm">
              <h3 className="text-xl font-semibold text-text-main mb-3">Our Mission</h3>
              <p className="text-sm text-text-muted leading-relaxed">
                To showcase the current capabilities of AI in long-form storytelling 
                and provide a transparent look at how machine creativity evolves.
              </p>
            </div>
            <div className="p-6 bg-bg-surface border border-border rounded-lg shadow-sm">
              <h3 className="text-xl font-semibold text-text-main mb-3">Open Source</h3>
              <p className="text-sm text-text-muted leading-relaxed">
                The project is open-source. You can explore the source code and 
                contribute to the platform&apos;s development on GitHub.
              </p>
            </div>
          </div>

          <div className="mt-12 p-8 bg-primary/10 border border-primary/20 rounded-xl text-center">
            <p className="text-text-main font-medium">
              Interested in contributing? Visit our <a href="https://github.com/prof-lijar/ai-generated-books" className="text-primary hover:underline font-bold">GitHub repository</a>.
            </p>
          </div>
        </div>
      </Container>
    </main>
  );
}
